version: "3.9"

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - db_postgres
      - db_mongo

  db_postgres:
    image: postgres
    environment:
      POSTGRES_DB: educative
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"

  db_mongo:
    image: mongo
    ports:
      - "27017:27017"
